Repository MLH-Fellowship/gitcord-bot, pull requests merged in 2021-07, with the labels that each got.

#1 Fix Unrelated Histories and Initial Discord Bot Creation
  .gitignore
  LICENSE
  README.md
  main.js
  package-lock.json
  package.json
Labels: merge

#2 Updated Readme and Deleted Duplicated License
  LICENSE
  LICENSE.md
  README.md
Labels: documentation

#3 Refactored code to create separate file for commands
  commands/github.js
  commands/testing.js
  main.js
Labels: enhancement

#5 Added GitHub API Integration
  github.js
  main.js
  package-lock.json
  package.json
Labels: enhancement

#6 Integrated GitHub API with Bot
  commands/github.js
  github.js
  main.js
  package-lock.json
Labels: enhancement

#8 Get tokens from the user
  commands/github.js
  commands/testing.js
  main.js
Labels: enhancement

#9 Comment posting works again
  commands/github.js
  main.js
Labels: enhancement

#13 Added help command
  commands/help.js
  main.js
Labels: enhancement

#11 Code Refactor & Bot Replies
  commands/github.js
  main.js
  package-lock.json
  package.json
Labels: bug, enhancement

#14 Refactored Help.js to Link Dynamically
  commands/help.js
  main.js
Labels: enhancement
