Repository MLH-Fellowship/gitcord-bot, pull requests merged in 2021-08, with the labels that each got.

#18 Code Freeze PR
  .gitignore
  LICENSE.md
  README.md
  commands/github.js
  commands/help.js
  commands/testing.js
  github.js
  main.js
  package-lock.json
  package.json
Labels: enhancement

#19 Up to Date Working Code
  .gitignore
  commands/github-issue-number.js
  commands/github-post-comment.js
  commands/github.info.js
  commands/github.js
  commands/help.js
  commands/testing.js
  main.js
  package-lock.json
  package.json
Labels: enhancement

#30 Refactor Post Issue Comment to Allow Multiple Arguments
  commands/github-issue-number.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  github.js
Labels: enhancement

#33 Adds Website Tech Scanner
  commands/tech-stack.js
  package-lock.json
  package.json
Labels: enhancement

#34 Implements Auto Assignment for GitHub Projects
  .github/workflows/project-assign.yml
  main.js
Labels: enhancement

#37 Added a Pull Request Template
  pull_request_template.md
Labels: documentation

#40 Fixed `-help github-info` command
  commands/github-info.js
Labels: enhancement

#43 Added GitHub Discussion Update Comment Functionality
  commands/github-update-standup.js
  package-lock.json
Labels: enhancement

#45 Added lighthouse stats
  commands/github.info.js
  commands/lighthouse.js
  commands/tech-stack.js
  package-lock.json
  package.json
Labels: enhancement

#47 Updated and Formatted Readme
  README.md
Labels: documentation

#48 Code Freeze - Week 2
  .github/workflows/project-assign.yml
  .gitignore
  README.md
  commands/github-info.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  commands/github.info.js
  commands/github.js
  commands/help.js
  commands/lighthouse.js
  commands/tech-stack.js
  commands/testing.js
  github.js
  main.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#52 Made a site for the bot
  .gitignore
  site/home.css
  site/home.html
Labels: enhancement

#51 Code Refactor
  .gitignore
  commands/github-info.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  commands/github.info.js
  commands/github.js
  commands/help.js
  commands/lighthouse.js
  commands/tech-stack.js
  github.js
  main.js
Labels: enhancement

#57 Show only 7 technologies for website scanning feature
  commands/tech-stack.js
Labels: enhancement

#55 Database Setup
  .gitignore
  commands/github-info.js
  commands/tech-stack.js
  github-token.txt
  package.json
Labels: enhancement

#61 Added usage section to help commands.
  commands/github-info.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  commands/help.js
  commands/lighthouse.js
  commands/tech-stack.js
  main.js
Labels: enhancement

#60 Refactored DB Code to use database.js
  commands/github-info.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  database.js
  github.js
Labels: enhancement

#63 Added a way to update GitHub token in DB with -github-info
  commands/github-info.js
  database.js
Labels: enhancement

#68 Added cards to Website
  site/home.css
  site/home.html
Labels: enhancement

#70 Main Octokit Refactoring
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  commands/help.js
  main.js
Labels: enhancement

#71 Refactored CSS Code
  site/home.css
  site/home.html
Labels: enhancement

#72 Lighthouse bug
  commands/lighthouse.js
Labels: enhancement

#74 Auto-Prefixing and Linting CSS
  .prettierrc
  .stylelintrc.json
  main.js
  package-lock.json
  package.json
  postcss.config.js
  site/home.css
Labels: enhancement

#77 Fixed Lighthouse on Headless Servers
  commands/lighthouse.js
Labels: bug

#78 Added navbar and logo
  site/assets/GitCordDarkLogo.png
  site/home.css
  site/home.html
Labels: enhancement

#79 Added Check for GitHub Token Validity
  commands/github-info.js
  github-token.txt
  main.js
Labels: bug, enhancement

#83 Delete Token Command
  commands/github-delete-token.js
  database.js
  main.js
Labels: enhancement

#87 Update Documentation
  README.md
Labels: documentation

#86 Week 3 Code Freeze
  .eslintrc.json
  .github/workflows/project-assign.yml
  .gitignore
  .prettierignore
  .prettierrc
  .stylelintrc.json
  README.md
  commands/github-delete-token.js
  commands/github-info.js
  commands/github-post-comment.js
  commands/github-post-standup.js
  commands/github-projects.js
  commands/github-update-standup.js
  commands/github.info.js
  commands/github.js
  commands/help.js
  commands/lighthouse.js
  commands/tech-stack.js
  database.js
  github.js
  main.js
  package-lock.json
  package.json
  postcss.config.js
  pull_request_template.md
  site/assets/GitCordDarkLogo.png
  site/assets/favicon.ico
  site/home.css
  site/home.html
Labels: enhancement
